name: Deploy Docs to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare docs (include submodule)
        run: |
          echo "Copying submodule into docs..."
          mkdir -p docs/KuoQuo-Pivot
          cp -r KuoQuo-Pivot/* docs/KuoQuo-Pivot/

      - name: Deploy docs folder to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages